@startuml

class Server implements Layers.DataLinkLayer, Protocols.ARP{
	-read_fd:Integer
	-write_fd:Integer
	-_mac_addr:mac_addr

	+Server(read_fd: Integer, write_fd: Integer, mac_addr: Mac)
	+run_serv()
	+run_cli()
	+send_bytes(bitstream: byte[])
	+receve_bytes():byte[]

 	+send_tram(payload: String, protocol: Integer)
    +receve_tram()
}

Server .> DataStruct.Tram : <<uses>>

package DataStruct {
	class Tram {
	 -mac_dest: mac_addr
	 -mac_src: mac_addr
	 -protocol: int
	 -payload: String

	 get_tram():byte*
	}
}

package Protocols {
	interface ARP {
		- send_arp_response()
		- send_arp_request(ip: Ip):
		- receve_arp_response(): Mac
		- receve_arp_request()
	}
}


package Layers {
	interface PhysicalLayer {
		+ send_bytes(bitstream: byte[])
		+ receve_bytes()
	}

	interface DataLinkLayer {
		+ send_tram(paquet: Paquet, ip_next_hop: Ip, protocol: Integer)
		+ receve_tram(bitstream: byte[])
	}

	interface NetworkLayer {
		+ send_paquet(segment: Segment, ip_dest: Ip)
		+ receve_paquet(paquet: Paquet)
	}

	interface TransportLayer {
		+ send_segment(message: String, port_dest: Integer, ip_dest: Ip)
		+ receve_segment(segment: Segment)
	}

	interface AppLayer {
		+ send_message(message: String)
		+ receve_message(message: String)
	}
}

@enduml
